[[1]]
input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
solution = 14

[[2]]
input = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"""
solution = 9


[[2]]
input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
solution = 34
