#!/usr/bin/env bash

###################
# Git hook to add a random emoji to the end of the commit message
#
# Install this commit-msg hook by running:
#   ln -s ../../commit-msg .git/hooks/commit-msg
###################

# Define an array of Christmas-themed emojis
christmas_emojis=(🎄 🎅 🎁 ☃️ ❄️ 🌟 🦌)

# Get the current commit message
commit_message=$(cat "$1")

# Check if the passed in string ends with any of the Christmas emojis
for emoji in "${christmas_emojis[@]}"; do
  if [[ "$commit_message" == *"$emoji" ]]; then
    # If the string ends with a Christmas emoji, exit
    exit 0
  fi
done

# Choose a random emoji from the array
chosen_emoji=${christmas_emojis[$RANDOM % ${#christmas_emojis[@]}]}

# Append the chosen emoji to the commit message
echo "${commit_message} ${chosen_emoji}" > "$1"
