[[1]]
input = """
 D
NC
ZMP
------------------
move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2
"""
solution = "CMZ"

[[2]]
input = """
 D
NC
ZMP
------------------
move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2
"""
solution = "MCD"
